# Generated by Django 4.2.20 on 2025-11-20 10:07

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.IntegerField(choices=[(0, 'deforestacion'), (1, 'parametros de cultivo'), (2, 'climatologia')])),
            ],
        ),
        migrations.CreateModel(
            name='File_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='media'), upload_to='datasets/')),
                ('date', models.DateTimeField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.IntegerField(choices=[(0, 'Raster'), (1, 'Polygon')])),
                ('source_crs', models.CharField(max_length=32)),
                ('data_rules', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tree_capitator.dataset')),
            ],
        ),
    ]
