# Generated by Django 4.2.20 on 2025-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_capitator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_model',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
