# Generated by Django 4.2.20 on 2025-11-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_capitator', '0003_dataset_subcategory_alter_file_model_file_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition_key', models.CharField(max_length=255, unique=True)),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='tree_capita_created_44d915_idx')],
            },
        ),
    ]
