# Usa una imagen base de Python 3.12.6
FROM python:3.12.6

# Establece un directorio de trabajo
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Instala las dependencias del sistema
RUN pip install --upgrade pip
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    libgdal-dev \
    python3-dev \
    python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip install gunicorn
RUN pip install openai
RUN pip install rasterio

# Descarga y compila GDAL 3.9.0
RUN wget https://download.osgeo.org/gdal/3.9.0/gdal-3.9.0.tar.gz && \
    tar -xzf gdal-3.9.0.tar.gz && \
    cd gdal-3.9.0 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    ldconfig

# Copia el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instala las dependencias de Python globalmente
RUN pip install --upgrade pip && pip install -r requirements.txt

# Configura el comando por defecto para ejecutar el contenedor
CMD ["/bin/bash"]
